blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path: /login_check

logout:
    path: /logout


#rutas_bundle:
#  resource: "@AppBundle/Resources/config/routing.yml"
#  prefix: /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#rutas_bundle:
#  resource: "@BlogBundle/Resources/config/routing.yml"
#  prefix: /



