pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: { _controller: AppBundle:Prueba:index,lang:es,name:nombre_defecto,page:1 }
    methods: [GET,POST]
    requirements:
        #name: \w+
        name: "[a-zA-Z]*"
        page: \d+
        lang: es|en|fr


